[0m17:51:35.482786 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1072b2ba0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1105779d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110577890>]}


============================== 17:51:35.485585 | 1e4b1a5e-45ec-4fd0-81ce-925f33eaa3da ==============================
[0m17:51:35.485585 [info ] [MainThread]: Running with dbt=1.9.4
[0m17:51:35.485928 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/Users/jkang/.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt deps', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:51:35.486327 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/jkang/Documents/GitHub/getting-started-with-dbt-on-snowflake/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:51:35.486686 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.040454585, "process_in_blocks": "0", "process_kernel_time": 0.196418, "process_mem_max_rss": "109641728", "process_out_blocks": "0", "process_user_time": 0.674032}
[0m17:51:35.486963 [debug] [MainThread]: Command `dbt deps` failed at 17:51:35.486911 after 0.04 seconds
[0m17:51:35.487133 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1105916e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1104bbd10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110421260>]}
[0m17:51:35.487274 [debug] [MainThread]: Flushing usage events
[0m17:51:35.663426 [debug] [MainThread]: An error was encountered while trying to flush usage events
